include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  exclude:
    - "android/app"
#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_declare_return_types: true
#    always_specify_types: true
    omit_local_variable_types: false