include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  exclude:
    - "android/app"
#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations